# [RNW-AUTOLINK] Auto-generated by @appsent-co/react-native-watchos.
# Re-run `expo prebuild` to regenerate.

platform :watchos, '9.0'

require_relative File.join(__dir__, '../../../cocoapods/autolink.rb')

if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
  config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"]
else
  config_command = ['node', '--no-warnings', '--eval', "require('expo/bin/autolinking')", 'expo-modules-autolinking', 'react-native-config', '--json', '--platform', 'ios']
end

use_watchos_modules!(:config_command => config_command)
