import Foundation
import ExpoModulesCore
import ReactNativeWatchOSCxx

/// Installs the non-UI Expo module runtime into one watch host's Hermes runtime.
/// Supply a fresh instance from `runtimeBindingFactory` for every host/reload.
public final class ExpoRuntimeBinding: NSObject, RNWRuntimeBinding {
    private let provider: ModulesProvider
    private var context: AppContext?
    private var installed = false

    public init(provider: ModulesProvider) {
        self.provider = provider
        super.init()
    }

    public func install(runtime: UnsafeMutableRawPointer, schedule: @escaping RNWJavaScriptScheduler) {
        precondition(!installed, "An ExpoRuntimeBinding cannot be reused across Hermes runtimes.")
        precondition(RNWCurrentJavaScriptRuntime() == runtime, "Expo installation must run on its host's JS queue.")
        installed = true
        let scheduler = RNWExpoScheduler(schedule: schedule)
        let context = AppContext()
        context.useModulesProvider(provider)
        self.context = context
        context.setRuntime(runtime, scheduler: scheduler.handle,
                           dispatch: RNWExpoScheduler.dispatchPointer(), schedulerOwner: scheduler)
    }

    public func invalidate() {
        // Called on the owning JS queue before Hermes releases its NativeState.
        // ExpoRuntime retains the scheduler; its host callback becomes a no-op
        // after teardown, including work already running on an async module queue.
        context?.destroy()
        context = nil
    }
}

/// Automatic entry point selected by the opt-in watch target's Info.plist.
/// The provider is generated by watchOS autolinking and compiled into that app.
@objc(RNWExpoRuntimeBindingFactory)
public final class ExpoRuntimeBindingFactory: NSObject, RNWRuntimeBindingFactory {
    public static func makeRuntimeBinding() -> RNWRuntimeBinding {
        guard let providerClass = NSClassFromString("RNWExpoModulesProvider") as? ModulesProvider.Type else {
            preconditionFailure(
                "[ReactNativeWatchOSExpo] RNWExpoModulesProvider is missing. " +
                "Enable expoModules in the watchOS config plugin and run prebuild/pod install."
            )
        }
        return ExpoRuntimeBinding(provider: providerClass.init())
    }
}
