import Foundation
import ObjectiveC
import ExpoModulesCore
import ReactNativeWatchOSCxx

/// Installs the non-UI Expo module runtime into one watch host's Hermes runtime.
/// Supply a fresh instance from `runtimeBindingFactory` for every host/reload.
public final class ExpoRuntimeBinding: NSObject, RNWRuntimeBinding {
    private nonisolated(unsafe) static var schedulerKey: UInt8 = 0
    private let provider: ModulesProvider
    private var context: AppContext?
    private var legacyRegistry: EXModuleRegistry?
    private var installed = false

    public init(provider: ModulesProvider) {
        self.provider = provider
        super.init()
    }

    public func install(runtime: UnsafeMutableRawPointer, schedule: @escaping RNWJavaScriptScheduler) {
        precondition(!installed, "An ExpoRuntimeBinding cannot be reused across Hermes runtimes.")
        installed = true
        let scheduler = RNWExpoScheduler(schedule: schedule)
        // Keep service instances local to this host; no global legacy provider.
        let registry = EXModuleRegistry(internalModules: [], exportedModules: [], singletonModules: [])
        let context = AppContext(legacyModuleRegistry: registry)
        if let fileSystem = context.fileSystem { registry.register(fileSystem) }
        registry.initialize()
        legacyRegistry = registry
        context.useModulesProvider(provider)
        self.context = context
        context.setRuntime(runtime, scheduler: scheduler.handle,
                           dispatch: RNWExpoScheduler.dispatchPointer())
        // Retain the opaque handle on Expo's wrapper, including when async module
        // work outlives AppContext.destroy(). No Expo source ownership hook needed.
        objc_setAssociatedObject(try! context.runtime, &Self.schedulerKey, scheduler,
                                 .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
    }

    public func invalidate() {
        // Called on the owning JS queue before Hermes releases its NativeState.
        // ExpoRuntime retains the scheduler; its host callback becomes a no-op
        // after teardown, including work already running on an async module queue.
        context?.destroy()
        context = nil
        legacyRegistry = nil
    }
}

/// Automatic entry point selected by the watch target's Info.plist.
/// The provider is generated by watchOS autolinking and compiled into that app.
@objc(RNWExpoRuntimeBindingFactory)
public final class ExpoRuntimeBindingFactory: NSObject, RNWRuntimeBindingFactory {
    public static func makeRuntimeBinding() -> RNWRuntimeBinding {
        guard let providerClass = NSClassFromString("RNWExpoModulesProvider") as? ModulesProvider.Type else {
            preconditionFailure(
                "[ReactNativeWatchOSExpo] RNWExpoModulesProvider is missing. " +
                "Enable expoModules in the watchOS config plugin and run prebuild/pod install."
            )
        }
        return ExpoRuntimeBinding(provider: providerClass.init())
    }
}
