// @ts-check
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');

// Stamped at the top of every generated `pods.rb` so we can recognize and
// safely overwrite our own output on the next prebuild. A user who hand-edits
// `targets/<name>/pods.rb` (removing the marker) is left alone.
const MARKER =
  '# [RNW-AUTOLINK] Auto-generated by @appsent-co/react-native-watchos.';

/**
 * Writes a `targets/<targetName>/pods.rb` file that:
 *   1. Sets `platform :watchos, <deploymentTarget>` for the target.
 *   2. Requires `cocoapods/autolink.rb` from the npm-installed
 *      `@appsent-co/react-native-watchos` package.
 *   3. Calls `use_watchos_modules!` so every third-party RN module whose
 *      podspec declares `:watchos =>` gets linked into the watch target.
 *
 * The Podfile that `@bacons/apple-targets` injects already auto-loads every
 * `targets/<name>/pods.rb` inside a matching `target '<name>' do ... end`
 * block (see the `apple-targets-extension-loader` glob at the bottom of the
 * generated Podfile), so we don't need to touch the Podfile itself.
 *
 * Bare-RN consumers (no Expo prebuild) skip this plugin entirely and hand-
 * write the equivalent block in their own Podfile.
 *
 * @typedef {object} Opts
 * @property {string} targetName - Watch target name; matches the
 *   `targets/<targetName>/` directory.
 * @property {string} [watchosDeploymentTarget] - Minimum watchOS version.
 *   Defaults to `"9.0"`, matching `WATCHOS_DEPLOYMENT_TARGET` in
 *   `scripts/build-xcframework.sh`.
 *
 * @param {import('@expo/config-plugins').ExpoConfig} config
 * @param {Opts} opts
 */
const withWatchAutolinking = (
  config,
  { targetName, watchosDeploymentTarget }
) => {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const targetDir = path.join(projectRoot, 'targets', targetName);
      if (!fs.existsSync(targetDir)) {
        // No matching target dir — apple-targets hasn't been set up, or the
        // user gave a wrong targetName. Other plugins in the chain will surface
        // a clearer error; silently skip here.
        return cfg;
      }

      // Resolve the absolute path to our shipped Ruby helper, then compute
      // a path relative to the generated `pods.rb` so the file is portable
      // across machines / pnpm-symlinked node_modules layouts.
      const pkgJsonPath = require.resolve(
        '@appsent-co/react-native-watchos/package.json',
        {
          paths: [projectRoot],
        }
      );
      const pkgDir = path.dirname(pkgJsonPath);
      const helperAbs = path.join(pkgDir, 'cocoapods', 'autolink.rb');
      const helperRel = path.relative(targetDir, helperAbs);

      const deploymentTarget = watchosDeploymentTarget || '9.0';

      // Reuse the iOS Podfile's resolver (Expo's autolinker, with a
      // community-CLI fallback gated by EXPO_USE_COMMUNITY_AUTOLINKING) so
      // both targets see byte-identical podspec paths. pnpm symlinks can
      // otherwise route the two invocations to different physical paths
      // and CocoaPods will reject the duplicate.
      const contents = [
        MARKER,
        '# Re-run `expo prebuild` to regenerate.',
        '',
        `platform :watchos, '${deploymentTarget}'`,
        '',
        `require_relative File.join(__dir__, '${helperRel}')`,
        '',
        "if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'",
        "  config_command = ['node', '-e', \"process.argv=['', '', 'config'];require('@react-native-community/cli').run()\"]",
        'else',
        "  config_command = ['node', '--no-warnings', '--eval', \"require('expo/bin/autolinking')\", 'expo-modules-autolinking', 'react-native-config', '--json', '--platform', 'ios']",
        'end',
        '',
        'use_watchos_modules!(:config_command => config_command)',
        '',
      ].join('\n');

      const podsRbPath = path.join(targetDir, 'pods.rb');
      if (fs.existsSync(podsRbPath)) {
        const existing = fs.readFileSync(podsRbPath, 'utf8');
        if (!existing.startsWith(MARKER)) {
          // User has a hand-managed pods.rb; leave it alone.
          return cfg;
        }
      }
      fs.writeFileSync(podsRbPath, contents);
      return cfg;
    },
  ]);
};

module.exports = withWatchAutolinking;
